# this compose holds apps for visualizing the status of docker containers and 
# keep information on other containers

version: "3.3"

services:
  dozzle:
    container_name: dozzle
    user: 16001:16000
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8888:8080
  
  watchtower:
    image: containrrr/watchtower
    user: 16002:16000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080

  prometheus:
    image: prom/prometheus
    user: 16003:16000
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ${BASE}/prometheus/config:/etc/prometheus
      - ${BASE}/prometheus/data:/prometheus

  grafana:
    image: grafana/grafana
    user: 16004:16000
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ${BASE}/grafana/data:/etc/grafana/provisioning/datasources

  uptime-kuma:
    image: louislam/uptime-kuma:1
    user: 16005:16000
    container_name: uptime-kuma
    volumes:
      - ${BASE}/uptime-kuma/data:/app/data
    ports:
      - 3001:3001  # <Host Port>:<Container Port>
    restart: always
