# this compose holds apps for visualizing the status of docker containers and 
# keep information on other containers

version: "3.3"

services:
  dozzle:
    container_name: dozzle
    # user: 16001:16000 # this doesnt seem to like a user, even with docker permissions, so lets ignore
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${BASE}/dozzle/data:/data
    ports:
      - 8888:8080
    environment:
      DOZZLE_AUTH_PROVIDER: simple
  
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    # user: 16002:16000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8070:8080

  prometheus:
    image: prom/prometheus
    user: 16003:16000
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ${BASE}/prometheus/config:/etc/prometheus
      - ${BASE}/prometheus/data:/prometheus

  grafana:
    image: grafana/grafana
    user: 16004:16000
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ${BASE}/grafana/data:/etc/grafana/provisioning/datasources

  uptime-kuma:
    image: louislam/uptime-kuma:1
    # user: 16005:16000 # also has to run as root
    container_name: uptime-kuma
    volumes:
      - ${BASE}/uptime-kuma/data:/app/data
    ports:
      - 3009:3001  # <Host Port>:<Container Port>
    restart: always
    
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    # user: 16006:16000 # also has issues not running as root
    ports:
      - 53:53/tcp # plain dns over tcp
      - 53:53/udp # plain dns over udp
      - 8090:80/tcp # http web interface
      - 3002:3000/tcp # initial setup web interface
    volumes:
      - ${BASE}/adguardhome/config:/opt/adguardhome/conf # app configuration
      - ${BASE}/adguardhome/work:/opt/adguardhome/work # app working directory

# tracks the speed from your home network
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker-home
    environment:
      - PUID=16007
      - PGID=16000
      - TZ=${TZ}
      - APP_KEY=${SPEEDTESTKEY} # generate a key here: https://speedtest-tracker.dev
      - DB_CONNECTION=sqlite
      - SPEEDTEST_SCHEDULE=*/15 * * * * # every 15 minutes
#      - SPEEDTEST_SERVERS=
#      - DB_HOST= #optional
#      - DB_PORT= #optional
#      - DB_DATABASE= #optional
#      - DB_USERNAME= #optional
#      - DB_PASSWORD= #optional
      - DISPLAY_TIMEZONE=${TZ} #optional
      - PRUNE_RESULTS_OLDER_THAN=0 #optional
    ports:
      - 8093:80
    volumes:
      - ${BASE}/speedtest-tracker/config/:/config
    restart: unless-stopped
