version: '3.3'

services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    network_mode: host
    environment:
      - PUID=15001
      - PGID=15000
      - TZ=${TZ}
    volumes:
      - ${BASE}/config/homeassistant-config:/config
    restart: unless-stopped
  esphome:
    container_name: esphome
    image: ghcr.io/esphome/esphome
    network_mode: host
    privileged: true
    volumes:
      - ${BASE}/config/esphome-config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
