version: '3.3'

services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    environment:
      - PUID=15001
      - PGID=15000
      - TZ=${TZ}
    volumes:
      - ${BASE}/config/homeassistant-config:/config
    network_mode: host
    restart: unless-stopped
  esphome:
    container_name: esphome
    image: ghcr.io/esphome/esphome
    user: 15002:15000
    privileged: true
    networks:
      - nginx-network
    volumes:
      - ${BASE}/config/esphome-config:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 6052:6052
    restart: always
networks:
  default:
    name: home-network
  nginx-network:
    external: true
