# compose for a general use personal wiki and could serve as a template for specific wiki copies in the future

version: '3.3'

services:
  dokuwiki-personal:
    image: lscr.io/linuxserver/dokuwiki:latest
    container_name: dokuwiki-personal
    environment:
      - PUID=13001
      - PGID=13000
      - TZ=Etc/UTC
    env_file:
      - .env
    volumes:
      - ${BASE}/data:/config
    networks:
      - wiki-personal-network
      - nginx-personalwiki
      - homepage-network
    ports:
      - 80:80
      - 443:443 #optional
    restart: unless-stopped

networks:
  wiki-personal-network:
    name: wiki-personal-network
  nginx-personalwiki:
    external: true
    name: nginx-personalwiki
  homepage-network:
    external: true
    name: homepage-network
