version: '3.3'

services:
  # for media browsing
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=10001
      - PGID=10000
      - UMASK=002
    ports:
      - '8096:8096'
    volumes:
      - ${BASE}/config/jellyfin:/config
      - MediaLibrary:/data
    networks:
      - media-network
      - nginx-network
      - homepage-network
    restart: 'unless-stopped'

  # for listening to audio books
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    user: 10002:10000
    environment:
      - TZ=${TZ}
      - UMASK=002
      - PUID=10002
      - PGID=10000
    ports:
      - 13378:80
    volumes:
      - ${BASE}/config/audiobookshelf:/config
      - MediaAudiobooks:/audiobooks
      - MediaPodcasts:/podcasts
      - MediaAudiobooksMetadata:/metadata
    networks:
      - media-network
      - nginx-network
      - homepage-network
    restart: unless-stopped

  # for music streaming
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    user: 10003:10000
    ports:
      - "4533:4533"
    environment:
      ND_SCANNER_SCHEDULE: 0 * * * *
      ND_LOGLEVEL: info  
      ND_BASEURL: ${ND_BASEURL}
      ND_DEFAULTTHEME: "Spotify-ish"
      ND_DEFAULTUIVOLUME: 50
    volumes:
      - ${BASE}/config/navidrome:/data
      - MediaMusic:/music:ro
    networks:
      - media-network
      - nginx-network
      - homepage-network
    restart: unless-stopped

volumes:
  MediaStorage:
    name: MediaStorage
    external: true
  MediaLibrary:
    name: MediaLibrary
    external: true
  MediaAudiobooks:
    name: MediaAudiobooks
    external: true
  MediaPodcasts:
    name: MediaPodcasts
    external: true
  MediaAudiobooksMetadata:
    name: MediaAudiobooksMetadata
    external: true
  MediaMusic:
    name: MediaMusic
    external: true

networks:
  default:
  nginx-network:
    external: true
    name: nginx-network
  media-network:
    external: true
    name: media-network
  homepage-network:
    external: true
    name: homepage-network
